In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
carbon = pd.read_csv(
    "../DATA/CLEANED DATA SETS/carbon_intensity.csv"
)

productivity = pd.read_csv(
    "../DATA/CLEANED DATA SETS/labour_productivity.csv"
)

electricity = pd.read_csv(
    "../DATA/CLEANED DATA SETS/electricity_consumption.csv"
)

renewables = pd.read_csv(
    "../DATA/CLEANED DATA SETS/renewable_energy_share.csv"
)

tax = pd.read_csv(
    "../DATA/CLEANED DATA SETS/carbon_tax.csv"
)

In [3]:
carbon.head()

         Country Country_Code  Year  Carbon_Intensity
0  ASEAN (Ember)          NaN  2000            572.58
1  ASEAN (Ember)          NaN  2001            570.27
2  ASEAN (Ember)          NaN  2002            572.68
3  ASEAN (Ember)          NaN  2003            577.02
4  ASEAN (Ember)          NaN  2004            583.64

In [4]:
productivity.head()

   Country  Year  Labour_Productivity
0  Albania  2005            10.353054
1  Albania  2006            11.228283
2  Albania  2007            11.995945
3  Albania  2008            14.754907
4  Albania  2009            15.838745

In [5]:
electricity.head()

     Country  Year  Electricity_Consumption
0  Australia  2010               220091.029
1  Australia  2011               223451.837
2  Australia  2012               222415.400
3  Australia  2013               218899.242
4  Australia  2014               225954.139

In [6]:
renewables.head()

                       Country Country_Code  Year  Renewable_Share
0                        Aruba          ABW  1990         0.300000
1  Africa Eastern and Southern          AFE  1990        60.842404
2                  Afghanistan          AFG  1990        23.000000
3   Africa Western and Central          AFW  1990        85.895442
4                       Angola          AGO  1990        72.300000

In [7]:
tax.head()

       Country Country_Code  Year  Carbon_Tax
0  Afghanistan          AFG  1989           0
1  Afghanistan          AFG  1990           0
2  Afghanistan          AFG  1991           0
3  Afghanistan          AFG  1992           0
4  Afghanistan          AFG  1993           0

In [8]:
carbon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6332 entries, 0 to 6331
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country           6332 non-null   object
 1   Country_Code      6020 non-null   object
 2   Year              6332 non-null   int64
 3   Carbon_Intensity  6332 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 198.0+ KB

In [9]:
productivity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4891 entries, 0 to 4890
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Country              4891 non-null   object
 1   Year                 4891 non-null   int64
 2   Labour_Productivity  4891 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 114.8+ KB

In [10]:
electricity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Country                  699 non-null    object
 1   Year                     699 non-null    int64
 2   Electricity_Consumption  699 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 16.5+ KB

In [11]:
renewables.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8234 entries, 0 to 8233
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Country          8234 non-null   object
 1   Country_Code     8234 non-null   object
 2   Year             8234 non-null   int64
 3   Renewable_Share  8234 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 257.4+ KB

In [12]:
tax.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7437 entries, 0 to 7436
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       7437 non-null   object
 1   Country_Code  7437 non-null   object
 2   Year          7437 non-null   int64
 3   Carbon_Tax    7437 non-null   int64
dtypes: int64(2), object(2)
memory usage: 232.5+ KB

In [13]:
sorted(carbon["Country"].unique())

['ASEAN (Ember)',
 'Afghanistan',
 'Africa',
 'Africa (Ember)',
 'Albania',
 'Algeria',
 'American Samoa',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Asia',
 'Asia (Ember)',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Cook Islands',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia',
 'Democratic Republic of Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'EU (Ember)',
 'East Timor',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Europe',
 'Europe (Ember)',
 'European Union (27)',
 'Falkland Islands',
 'Faroe Islands',
 'Fiji',
 'Finland',
 'France',
 'French Guiana',
 'French Polynesia',
 'G20 (Ember)',
 'G7 (Ember)',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'High-income countries',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latin America and Caribbean (Ember)',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Lithuania',
 'Low-income countries',
 'Lower-middle-income countries',
 'Luxembourg',
 'Macao',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Martinique',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Middle East (Ember)',
 'Moldova',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North America',
 'North America (Ember)',
 'North Korea',
 'North Macedonia',
 'Norway',
 'OECD (Ember)',
 'Oceania',
 'Oceania (Ember)',
 'Oman',
 'Pakistan',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Reunion',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Helena',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Pierre and Miquelon',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South America',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'United States Virgin Islands',
 'Upper-middle-income countries',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'Western Sahara',
 'World',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [14]:
sorted(productivity["Country"].unique())

['Albania',
 'Algeria',
 'Angola',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahrain',
 'Bangladesh',
 'Belarus',
 'Belgium',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Bulgaria',
 'Burkina Faso',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Congo',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cyprus',
 'Czechia',
 'Democratic Republic of Congo',
 'Denmark',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'Estonia',
 'Ethiopia',
 'Finland',
 'France',
 'Gabon',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Guatemala',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kuwait',
 'Kyrgyzstan',
 'Latvia',
 'Lebanon',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Mali',
 'Malta',
 'Mauritius',
 'Mexico',
 'Moldova',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Netherlands',
 'New Zealand',
 'Niger',
 'Nigeria',
 'North Macedonia',
 'Norway',
 'Oman',
 'Pakistan',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'South Africa',
 'South Korea',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [15]:
sorted(electricity["Country"].unique())

['Australia',
 'Austria',
 'Belgium',
 'Canada',
 'Chile',
 'Colombia',
 'Costa Rica',
 'Czech Republic',
 'Denmark',
 'Estonia',
 'Finland',
 'France',
 'Germany',
 'Greece',
 'Hungary',
 'IEA Total',
 'Iceland',
 'Ireland',
 'Italy',
 'Japan',
 'Korea',
 'Latvia',
 'Lithuania',
 'Luxembourg',
 'Mexico',
 'Netherlands',
 'New Zealand',
 'Norway',
 'OECD Americas',
 'OECD Asia Oceania',
 'OECD Europe',
 'OECD Total',
 'Poland',
 'Portugal',
 'Republic of Turkiye',
 'Slovak Republic',
 'Slovenia',
 'Spain',
 'Sweden',
 'Switzerland',
 'United Kingdom',
 'United States']

In [16]:
sorted(renewables["Country"].unique())

['Afghanistan',
 'Africa Eastern and Southern',
 'Africa Western and Central',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Arab World',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas, The',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Caribbean small states',
 'Cayman Islands',
 'Central African Republic',
 'Central Europe and the Baltics',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo, Dem. Rep.',
 'Congo, Rep.',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Curacao',
 'Cyprus',
 'Czechia',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Early-demographic dividend',
 'East Asia & Pacific',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (excluding high income)',
 'Ecuador',
 'Egypt, Arab Rep.',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Euro area',
 'Europe & Central Asia',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (excluding high income)',
 'European Union',
 'Faroe Islands',
 'Fiji',
 'Finland',
 'Fragile and conflict affected situations',
 'France',
 'French Polynesia',
 'Gabon',
 'Gambia, The',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Heavily indebted poor countries (HIPC)',
 'High income',
 'Honduras',
 'Hong Kong SAR, China',
 'Hungary',
 'IBRD only',
 'IDA & IBRD total',
 'IDA blend',
 'IDA only',
 'IDA total',
 'Iceland',
 'India',
 'Indonesia',
 'Iran, Islamic Rep.',
 'Iraq',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 "Korea, Dem. People's Rep.",
 'Korea, Rep.',
 'Kuwait',
 'Kyrgyz Republic',
 'Lao PDR',
 'Late-demographic dividend',
 'Latin America & Caribbean',
 'Latin America & Caribbean (excluding high income)',
 'Latin America & the Caribbean (IDA & IBRD countries)',
 'Latvia',
 'Least developed countries: UN classification',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Low & middle income',
 'Low income',
 'Lower middle income',
 'Luxembourg',
 'Macao SAR, China',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia, Fed. Sts.',
 'Middle East, North Africa, Afghanistan & Pakistan',
 'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)',
 'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)',
 'Middle income',
 'Moldova',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North America',
 'North Macedonia',
 'Northern Mariana Islands',
 'Norway',
 'OECD members',
 'Oman',
 'Other small states',
 'Pacific island small states',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Post-demographic dividend',
 'Pre-demographic dividend',
 'Puerto Rico (US)',
 'Qatar',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'Samoa',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Sint Maarten (Dutch part)',
 'Slovak Republic',
 'Slovenia',
 'Small states',
 'Solomon Islands',
 'Somalia, Fed. Rep.',
 'South Africa',
 'South Asia',
 'South Asia (IDA & IBRD)',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'St. Kitts and Nevis',
 'St. Lucia',
 'St. Vincent and the Grenadines',
 'Sub-Saharan Africa',
 'Sub-Saharan Africa (IDA & IBRD countries)',
 'Sub-Saharan Africa (excluding high income)',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syrian Arab Republic',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkiye',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Upper middle income',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela, RB',
 'Viet Nam',
 'Virgin Islands (U.S.)',
 'West Bank and Gaza',
 'World',
 'Yemen, Rep.',
 'Zambia',
 'Zimbabwe']

In [17]:
sorted(tax["Country"].unique())

['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia',
 'Democratic Republic of Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'East Timor',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macao',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia (country)',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Korea',
 'North Macedonia',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Vatican',
 'Venezuela',
 'Vietnam',
 'Western Sahara',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [18]:
countries = [
    "United States",
    "Germany",
    "France",
    "Norway",
    "Poland",
    "Japan"
]

for country in countries:
    print(country)
    print("Carbon:", country in carbon["Country"].values)
    print("Productivity:", country in productivity["Country"].values)
    print("Electricity:", country in electricity["Country"].values)
    print("Renewables:", country in renewables["Country"].values)
    print("Tax:", country in tax["Country"].values)
    print("-"*30)

United States
Carbon: True
Productivity: True
Electricity: True
Renewables: True
Tax: True
------------------------------
Germany
Carbon: True
Productivity: True
Electricity: True
Renewables: True
Tax: True
------------------------------
France
Carbon: True
Productivity: True
Electricity: True
Renewables: True
Tax: True
------------------------------
Norway
Carbon: True
Productivity: True
Electricity: True
Renewables: True
Tax: True
------------------------------
Poland
Carbon: True
Productivity: True
Electricity: True
Renewables: True
Tax: True
------------------------------
Japan
Carbon: True
Productivity: True
Electricity: True
Renewables: True
Tax: True
------------------------------

In [19]:
print("Carbon:", carbon["Year"].min(), "-", carbon["Year"].max())
print("Productivity:", productivity["Year"].min(), "-", productivity["Year"].max())
print("Electricity:", electricity["Year"].min(), "-", electricity["Year"].max())
print("Renewables:", renewables["Year"].min(), "-", renewables["Year"].max())
print("Tax:", tax["Year"].min(), "-", tax["Year"].max())

Carbon: 1990 - 2025
Productivity: 1950 - 2023
Electricity: 2010 - 2026
Renewables: 1990 - 2022
Tax: 1989 - 2025

In [20]:
len(set(productivity["Country"]))
len(set(carbon["Country"]))
len(set(electricity["Country"]))
len(set(renewables["Country"]))
len(set(tax["Country"]))

201

In [21]:
common_countries = (
    set(productivity["Country"])
    & set(carbon["Country"])
    & set(electricity["Country"])
    & set(renewables["Country"])
    & set(tax["Country"])
)

print("Common countries:", len(common_countries))

Common countries: 32

In [22]:
master = productivity.merge(
    carbon,
    on=["Country", "Year"],
    how="inner"
)

master = master.merge(
    electricity,
    on=["Country", "Year"],
    how="inner"
)

master = master.merge(
    renewables,
    on=["Country", "Year"],
    how="inner"
)

master = master.merge(
    tax,
    on=["Country", "Year"],
    how="inner"
)

In [23]:
master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 369 entries, 0 to 368
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Country                  369 non-null    object
 1   Year                     369 non-null    int64
 2   Labour_Productivity      369 non-null    float64
 3   Country_Code_x           369 non-null    object
 4   Carbon_Intensity         369 non-null    float64
 5   Electricity_Consumption  369 non-null    float64
 6   Country_Code_y           369 non-null    object
 7   Renewable_Share          369 non-null    float64
 8   Country_Code             369 non-null    object
 9   Carbon_Tax               369 non-null    int64
dtypes: float64(4), int64(2), object(4)
memory usage: 29.0+ KB

In [24]:
master.head()

,Country,Year,Labour_Productivity,Country_Code_x,Carbon_Intensity,Electricity_Consumption,Country_Code_y,Renewable_Share,Country_Code,Carbon_Tax
0,Australia,2010,66.426834,AUS,775.67,220091.029,AUS,8.2,AUS,0
1,Australia,2011,68.341060,AUS,749.42,223451.837,AUS,8.3,AUS,0
2,Australia,2012,67.268910,AUS,746.99,222415.400,AUS,8.3,AUS,0
3,Australia,2013,69.426270,AUS,726.16,218899.242,AUS,9.2,AUS,0
4,Australia,2014,69.183320,AUS,734.18,225954.139,AUS,9.3,AUS,0

In [25]:
master.shape

(369, 10)

In [26]:
master.columns

Index(['Country', 'Year', 'Labour_Productivity', 'Country_Code_x',
       'Carbon_Intensity', 'Electricity_Consumption', 'Country_Code_y',
       'Renewable_Share', 'Country_Code', 'Carbon_Tax'],
      dtype='object')

In [27]:
master["Country"].nunique()

32

In [28]:
master["Year"].min(), master["Year"].max()

(2010, 2021)

In [29]:
master.to_csv(
    "../DATA/CLEANED DATA SETS/master_panel.csv",
    index=False
)

In [30]:
master = master.drop(
    columns=[
        "Country_Code_x",
        "Country_Code_y"
    ]
)

master.head()

,Country,Year,Labour_Productivity,Carbon_Intensity,Electricity_Consumption,Renewable_Share,Country_Code,Carbon_Tax
0,Australia,2010,66.426834,775.67,220091.029,8.2,AUS,0
1,Australia,2011,68.341060,749.42,223451.837,8.3,AUS,0
2,Australia,2012,67.268910,746.99,222415.400,8.3,AUS,0
3,Australia,2013,69.426270,726.16,218899.242,9.2,AUS,0
4,Australia,2014,69.183320,734.18,225954.139,9.3,AUS,0

In [31]:
master.to_csv(
    "../DATA/CLEANED DATA SETS/master_panel.csv",
    index=False
)

In [33]:
master.columns

Index(['Country', 'Year', 'Labour_Productivity', 'Carbon_Intensity',
       'Electricity_Consumption', 'Renewable_Share', 'Country_Code',
       'Carbon_Tax'],
      dtype='object')

In [34]:
master = master.drop(
    columns=["Country_Code"]
)

master.columns

Index(['Country', 'Year', 'Labour_Productivity', 'Carbon_Intensity',
       'Electricity_Consumption', 'Renewable_Share', 'Carbon_Tax'],
      dtype='object')

In [35]:
master.to_csv(
    "../DATA/CLEANED DATA SETS/master_panel.csv",
    index=False
)

In [37]:
import os

In [38]:
os.listdir("../DATA/RAW DATA SETS")

['AI productivity contribution not important',
 'Carbon emissions not important',
 'Carbon intensity',
 'Carbon Tax Level',
 'Datacenter Power demand',
 'Electricity consumption',
 'Labour Productivity',
 'Renewable energy share',
 'Water usage not important']

In [39]:
os.listdir("../DATA/RAW DATA SETS/Datacenter Power demand")

['data-centers-share-electricity-demand.csv']

In [40]:
dc_df = pd.read_csv(
    "../DATA/RAW DATA SETS/Datacenter Power demand/data-centers-share-electricity-demand.csv"
)

In [41]:
dc_df.head()

,Entity,Code,Year,Share of total electricity demand coming from data centers
0,Africa (IEA),NaN,2020,0.128485
1,Africa (IEA),NaN,2023,0.139677
2,Africa (IEA),NaN,2024,0.144970
3,Africa (IEA),NaN,2025,0.249953
4,Asia Pacific (IEA),NaN,2020,0.718906

In [42]:
dc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 4 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   Entity                                                      40 non-null     object
 1   Code                                                        12 non-null     object
 2   Year                                                        40 non-null     int64
 3   Share of total electricity demand coming from data centers  40 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.4+ KB

In [43]:
dc_df.columns

Index(['Entity', 'Code', 'Year',
       'Share of total electricity demand coming from data centers'],
      dtype='object')

In [44]:
dc_df.shape

(40, 4)

In [45]:
sorted(dc_df["Year"].unique())

[np.int64(2020), np.int64(2023), np.int64(2024), np.int64(2025)]

In [46]:
dc_df["Year"].min(), dc_df["Year"].max()

(2020, 2025)

In [47]:
dc_df["Entity"].unique()

array(['Africa (IEA)', 'Asia Pacific (IEA)',
       'Central and South America (IEA)', 'China', 'Europe (IEA)',
       'Middle East (IEA)', 'North America (IEA)', 'United States',
       'World', 'World excl. United States and China'], dtype=object)

In [53]:
%whos

Variable               Type         Data/Info
---------------------------------------------
carbon                 DataFrame                Country Count<...>\n[6332 rows x 4 columns]
common_countries       set          {'Finland', 'United Kingd<...>, 'Belgium', 'Lithuania'}
countries              list         n=6
country                str          Japan
dataframe_columns      function     <function dataframe_colum<...>ns at 0x000001F93769B9C0>
dataframe_hash         function     <function dataframe_hash at 0x000001F93B776520>
dc_df                  DataFrame                             <...>      0.863691
dtypes_str             function     <function dtypes_str at 0x000001F93B7756C0>
electricity            DataFrame               Country  Year <...>n\n[699 rows x 3 columns]
get_dataframes         function     <function get_dataframes at 0x000001F93B774FE0>
getpass                module       <module 'getpass' from 'C<...>conda3\\Lib\\getpass.py'>
hashlib                module       <module 'hashlib' from 'C<...>conda3\\Lib\\hashlib.py'>
import_pandas_safely   function     <function import_pandas_s<...>ly at 0x000001F93238DC60>
is_data_frame          function     <function is_data_frame at 0x000001F935A7D300>
json                   module       <module 'json' from 'C:\\<...>\Lib\\json\\__init__.py'>
master                 DataFrame               Country  Year <...>n\n[369 rows x 7 columns]
np                     module       <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
os                     module       <module 'os' from 'C:\\Us<...>\\anaconda3\\Lib\\os.py'>
pd                     module       <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
plt                    module       <module 'matplotlib.pyplo<...>\\matplotlib\\pyplot.py'>
productivity           DataFrame           Country  Year  Lab<...>\n[4891 rows x 3 columns]
renewables             DataFrame                             <...>\n[8234 rows x 4 columns]
tax                    DataFrame              Country Country<...>\n[7437 rows x 4 columns]

In [54]:
master[['Labour_Productivity',
        'Carbon_Intensity',
        'Electricity_Consumption',
        'Renewable_Share',
        'Carbon_Tax']].corr()

,Labour_Productivity,Carbon_Intensity,Electricity_Consumption,Renewable_Share,Carbon_Tax
Labour_Productivity,1.000000,-0.395833,0.147580,0.178288,0.040157
Carbon_Intensity,-0.395833,1.000000,0.202100,-0.596476,-0.198611
Electricity_Consumption,0.147580,0.202100,1.000000,-0.270951,-0.162107
Renewable_Share,0.178288,-0.596476,-0.270951,1.000000,0.418758
Carbon_Tax,0.040157,-0.198611,-0.162107,0.418758,1.000000

In [55]:
master[['Labour_Productivity',
        'Carbon_Intensity',
        'Electricity_Consumption',
        'Renewable_Share',
        'Carbon_Tax']].describe()

,Labour_Productivity,Carbon_Intensity,Electricity_Consumption,Renewable_Share,Carbon_Tax
count,369.000000,369.000000,3.690000e+02,369.000000,369.000000
mean,60.236930,324.294607,2.906790e+05,24.218970,0.504065
std,22.212461,209.922046,6.975428e+05,16.658624,0.500662
min,13.976612,25.920000,6.119861e+03,3.200000,0.000000
25%,40.649040,169.990000,3.897570e+04,11.600000,0.000000
50%,62.096140,296.920000,8.224175e+04,20.600000,1.000000
75%,75.334010,493.070000,2.481987e+05,31.300000,1.000000
max,144.203830,893.030000,4.042840e+06,82.900000,1.000000